### ISSUE TITLE
Deobfuscated!

### ISSUE THREAD

**Issue by trenbolone** [futzumi/Kahoot-Hack#11]
if (!document.querySelector("#zumimenu") && location.href.includes("https://kahoot.it/")) {
    let zumimenu = document.createElement("div");
    zumimenu.id = "zumimenu";
    zumimenu.style = "position: absolute; top: 0px; \nleft: 0px; width: 100%; height: 100%; margin: 0px; display: flex;\n            flex-direction: column;\n            z-index: 1000; /* Ensure it's on top */\n            pointer-events: none;\n            user-select: none;\n            ";
    zumimenu.innerHTML = "  <div style=\"pointer-events: auto;width: 40%; height: 60%; background: #25292e; position: relative; top: 0; left: 0; margin: 15px; display: block;\">\n        <div style=\"position: absolute; top: 0px; left: 0px; display: flex; text-align: center; justify-content: center; align-items: center;\">\n            <img style=\"height: 100%; width: 40%;\" src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Kahoot_Logo.svg/1280px-Kahoot_Logo.svg.png\">\n            <span class=\"zumi-close\" style=\"position: absolute; top: 0; right: 15px; color: ghostwhite; margin: 25px; cursor: pointer;\">X</span>\n        </div>\n        <div class=\"zumi-options\" style=\"position:absolute; top: 10%; left: 0px; width: 100%; height: 90%; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center;\">\n            <span style=\"color: #441090; font-size: 15px; margin-bottom: 10px;\">\n                Look at your teacher's URL bar and copy the game ID.<br>\n                Ex. https://play.kahoot.it/v2/lobby?quizId=[COPY CODE HERE]\n            </span>\n            <input id=\"zumi-launch_inp\" style=\"width: 80%; height: 50px; margin-top: 10px; background: transparent; border: 2px solid ghostwhite; font-size: 18px; outline:none; color: ghostwhite; text-align: center;\" value=\"\">\n       <button id=\"launch-zumi\" style=\"margin-top: 10px; padding: 10px 20px; background-color: #441090; color: white; border: none; border-radius: 5px; cursor: pointer;\">\n                LAUNCH\n            </button>\n              <span style=\"color:rgb(105, 105, 105); font-size: 15px; margin-top:30px;\">\n               Press K to kill the menu/hacks<br>\n               Press T to toggle the menu\n            </span>\n            </div>\n    </div>";
    document.body.appendChild(zumimenu);
    document.querySelector(".zumi-close").addEventListener('click', function () {
      document.querySelector("#zumimenu").remove();
    });
    document.querySelector("#launch-zumi").addEventListener("click", function () {
      const _0x17e404 = {};
      var _0x26668a = document.querySelector("#zumi-launch_inp").value;
      _0x17e404.getQuestionData = function (_0x3c8a13) {
        fetch("https://kahoot.it/rest/kahoots/" + _0x26668a, {
          'headers': {
            'accept': "*/*",
            'accept-language': "en-US,en;q=0.9",
            'cache-control': "no-cache",
            'pragma': "no-cache",
            'sec-ch-ua': "\"Google Chrome\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"",
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': "\"Windows\"",
            'sec-fetch-dest': "empty",
            'sec-fetch-mode': "cors",
            'sec-fetch-site': "same-origin"
          },
          'referrer': "https://kahoot.it/",
          'referrerPolicy': "strict-origin-when-cross-origin",
          'body': null,
          'method': 'GET',
          'mode': "cors",
          'credentials': "include"
        }).then(_0x4b2562 => {
          if (!_0x4b2562.ok) {
            alert("An error occured. Make sure you followed the instructions correctly and typed the quiz ID correctly.\nIf problems continue, create an issue on my github.\nhttps://github.com/futzumi/Kahoot-Hack");
            document.querySelector("#zumimenu").remove();
          }
          return _0x4b2562.json();
        }).then(_0x223616 => {
          eval(_0x3c8a13);
        })['catch'](_0x4d5a19 => {
          alert("An error occured. Make sure you followed the instructions correctly and typed the quiz ID correctly.\nIf problems continue, create an issue on my github.\nhttps://github.com/futzumi/Kahoot-Hack");
          document.querySelector("#zumimenu").remove();
        });
      };
      document.querySelector(".zumi-options").innerHTML = "<style>  .toggle-container {\n            display: flex;\n            align-items: center;\n            margin: 10px 0;\n        }\n\n        .toggle {\n            position: relative;\n            display: inline-block;\n            width: 60px;\n            height: 34px;\n            margin-left: 20px;\n        }\n\n        .toggle input {\n            opacity: 0;\n            width: 0;\n            height: 0;\n        }\n\n        .slider {\n            position: absolute;\n            cursor: pointer;\n            top: 0;\n            left: 0;\n            right: 0;\n            bottom: 0;\n            background-color:rgb(64, 70, 78);\n            transition: .4s;\n            border-radius: 34px;\n        }\n\n        .slider:before {\n            position: absolute;\n            content: \"\";\n            height: 26px;\n            width: 26px;\n            left: 4px;\n            bottom: 4px;\n            background-color: white;\n            transition: .4s;\n            border-radius: 50%;\n        }\n\n        input:checked + .slider {\n            background-color: #441090;\n        }\n\n        input:checked + .slider:before {\n            transform: translateX(26px);\n        }</style>\n    <div style=\"color:ghostwhite; font-size: 24px; margin-right: 20px; justify-content: center; text-align: center; align-items: center; display: flex\">Rounded Answers <label class=\"toggle\">\n            <input id=\"roundAnswersToggle\" type=\"checkbox\">\n            <span class=\"slider\"></span>\n        </label>\n        </div>\n         <span style=\"color:rgb(105, 105, 105); font-size: 15px; margin-top:30px;\">\n               Press K to kill the menu/hacks<br>\n               Press T to toggle the menu\n            </span>";
      setInterval(function () {
        try {
          if (document.querySelector("#roundAnswersToggle").checked) {
            _0x17e404.roundAnswers = true;
          } else {
            _0x17e404.roundAnswers = false;
          }
        } catch (_0x261553) {}
      });
      _0x17e404.getQuestionData("setInterval(function() {\n                    try {\n                      var questionData = response.questions;\n                      var currentProblem = JSON.parse(localStorage.getItem(\"kahoot-game_session\")).questionNumber;\n                      var questionChoices = questionData[currentProblem].choices;\n                      var correctAnswer;\n                     if (questionChoices.length >= 2 && questionChoices.length <= 4) {\n    for (let i = 0; i < questionChoices.length; i++) {\n        if (questionChoices[i].correct) {\n            correctAnswer = questionChoices[i];\n            break; // Exit the loop once the correct answer is found\n        }\n    }\n}\n    \n                     if (kahoot.roundAnswers) {\n                      document.querySelector('[data-functional-selector=\"answer-' + questionChoices.indexOf(correctAnswer) + '\"]').style.borderRadius = '30px';\n                   }\n               \n          } catch (a) {\n                     }\n                  })");
    });
  }
  document.addEventListener("keydown", function (_0x1b4fac) {
    if (_0x1b4fac.key === 't' || _0x1b4fac.key === 'T') {
      if (document.querySelector("#zumimenu").style.visibility === "hidden") {
        document.querySelector("#zumimenu").style.visibility = "visible";
      } else {
        document.querySelector("#zumimenu").style.visibility = "hidden";
      }
    }
  });
  document.addEventListener("keydown", function (_0x51c808) {
    if (_0x51c808.key === 'k' || _0x51c808.key === 'K') {
      document.querySelector("#zumimenu").remove();
      kahoot.roundAnswers = false;
    }
  });

**Comment by futzumi** [comment]
i rebuke ts
