### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by pazza2234** [futzumi/Kahoot-Hack#3]
1. fix for private kahoots (requres shape input)
2. add gui (e.g/base: https://github.com/futzumi/Kahoot-Hack/issues)
3. quick disable

please and thanks. also, I know it would probaly get patched quicker but if it is open source it can be developed faster and bugs fixed quicker.

**Comment by bahillybeans** [comment]
You could make it so even if you answer super late you still get max points

**Comment by Pro-AndySong** [comment]
> You could make it so even if you answer super late you still get max points

Thats not possible because its Kahoot side that gives the points, not the client. It ranks the fastest down to the slowest answers and distributes points accordingly.

**Comment by futzumi** [comment]
> > You could make it so even if you answer super late you still get max points
> 
> Thats not possible because its Kahoot side that gives the points, not the client. It ranks the fastest down to the slowest answers and distributes points accordingly.

Its possible.

**Comment by futzumi** [comment]
> 1. fix for private kahoots (requres shape input)
> 2. add gui (e.g/base: https://github.com/futzumi/Kahoot-Hack/issues)
> 3. quick disable
> 
> please and thanks. also, I know it would probaly get patched quicker but if it is open source it can be developed faster and bugs fixed quicker.

I don't plan to update any of my bookmarklet hacks any further. The word going around is that the board of education in their region blocked bookmarklets. And that issue is also a problem at my school. I don't feel the need to make hacks that a small percentage of people can use, including myself

**Comment by futzumi** [comment]
> 1. fix for private kahoots (requres shape input)
> 2. add gui (e.g/base: https://github.com/futzumi/Kahoot-Hack/issues)
> 3. quick disable
> 
> please and thanks. also, I know it would probaly get patched quicker but if it is open source it can be developed faster and bugs fixed quicker.

GUI added with a kill and toggle keybind
