### ISSUE TITLE
It doesnt work.

### ISSUE THREAD

**Issue by jaj1324qewr** [futzumi/Kahoot-Hack#5]
I did everything you said, copying it, turning it into a bookmarklet, going into a game and everything. it doesnt do anything.

**Comment by qLeooo** [comment]
try to paste it in the browser console but idk if this even still works or is safe

**Comment by RandomChannel25** [comment]
you have to paste it into the console, use F12

**Comment by futzumi** [comment]
> I did everything you said, copying it, turning it into a bookmarklet, going into a game and everything. it doesnt do anything.

Paste it into your browser console. It is also pretty common for bookmarklets to be disabled
