### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by TheBozzz34** [futzumi/Kahoot-Hack#6]
Why is this obfuscated? Seems kinda pointless unless its trying to hide something sketchy. Not saying it is, and so far it looks clean, just something I wanted to ask about.

**Comment by futzumi** [comment]
this should be common sense, but it is to make the code harder to patch.

**Comment by DoxrGitHub** [comment]
no, you're just an idiot. anything you do, the Kahoot team could reverse; making the code obfuscated doesn't do shit

**Comment by futzumi** [comment]
> no, you're just an idiot. anything you do, the Kahoot team could reverse; making the code obfuscated doesn't do shit

Even if they can reverse it, it takes them extra time and effort. Another note, this is my code so if you have a problem with it make ur own ong. I can do what I want with my projects.

**Comment by DoxrGitHub** [comment]
ok whatever you say  buddy

**Comment by HighseasHackClub** [comment]
> > no, you're just an idiot. anything you do, the Kahoot team could reverse; making the code obfuscated doesn't do shit
> 
> Even if they can reverse it, it takes them extra time and effort. Another note, this is my code so if you have a problem with it make ur own ong. I can do what I want with my projects.

bro folded your a little restart(btw obfuscating it provides no added security but since ur a skid you wouldnt know that)
