### ISSUE TITLE
New idea

### ISSUE THREAD

**Issue by Theloo88** [futzumi/Kahoot-Hack#8]
make a gui

All answers correct
Auto answer
Choose how much precent you want
Bot filler

etc

**Comment by LabyCatUser** [comment]
this script is from may 2023, i dont think its gonna be updated anymore, you can make a one yourself if you need it

**Comment by futzumi** [comment]
> this script is from may 2023, i dont think its gonna be updated anymore, you can make a one yourself if you need it

The script was just updated ho

**Comment by futzumi** [comment]
> make a gui
> 
> All answers correct Auto answer Choose how much precent you want Bot filler
> 
> etc

gui done
