### ISSUE TITLE
It's not working showing an error

### ISSUE THREAD

**Issue by azfact160** [futzumi/Kahoot-Hack#9]
There was a kahoot but it didn't work on that. 
Showed an error.
An error occurred Make sure you followed the instructions correctly and typed the quiz ID correctly. 
If problem continues create an issue on my Github. 

Get ..... 400 vendor js.21

**Comment by azfact160** [comment]
Couldn't upload previously 
![Uploading IMG20241222140846.jpg…]()

**Comment by azfact160** [comment]
![Uploading IMG20241222142508.jpg…]()

**Comment by azfact160** [comment]
![Uploading IMG20241222142508.jpg…]()

**Comment by futzumi** [comment]
enter the quiz id correctly
